### ISSUE TITLE
Error: Couldn't find preset "module:metro-react-native-babel-preset"

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#6]
First: Can i store/get objects with vasern in/from the local storage at any time over the different files?

And second: Why is there a second react-native module in vasern installed (i have already installed react native normally!)? I have the problem that i cannot run it with two of them!
And when i delete react-native there is another issue about babel!

**Comment by hieunc229** [comment]
Hi @apppro123 

_**First**:_ Can you clarify what are "different files"? Also since Vasern is a local storage itself, I am confused about "the local storage" that you mentioned? Are you trying to sync data with an exsiting local storage? (It'd be great if you can provide a specific example)

Sure you can store and get objects with Vasern at any time. Though it need [a schema](https://vasern.com/docs/write-schema-setup-vasern) and might need to convert the format between 2 local storage.

**_Second_**: There are a few things need to be clean up in the "package.json". I'll have a look and push a fix within today

**Comment by hieunc229** [comment]
I have pushed a fix (clean up dependencies) https://github.com/vasern/vasern/commit/9b73f9bfcc0f59084904f89037cf385fb3b28325

You can remove and reinstall the lastest version (0.2.9) to apply changes

**Comment by apppro123** [comment]
At the moment i get this issue (after updating):
error: bundling failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "C:\\Users\\kalla\\OwnApp\\node_modules\\vasern"

**Comment by hieunc229** [comment]
It might related to this issue https://github.com/facebook/react-native/issues/21241#issuecomment-423610383. There are also severals fixes in the same topic

**Comment by apppro123** [comment]
After i deleted .babelrc it build it but on the screen it shows another error related to Document.js

for example the last line Document.import(Queryable);
What does this line do? And why is not the import at the beginning of this file like every other import?
And with Queryable, is the file Queryable.js meant?

**Comment by apppro123** [comment]
After i removed this line (line 538 in Document.js) it worked (i can now import Vasern from "vasern")

**Comment by hieunc229** [comment]
Vasern has a modular architecture (basically it was built in different parts and then plug in together).

When you removed `Document.import(Queryable)`, you have just detached the all retrieve and filter items functions. So the `Document.data()` and `Document.get()` didn't works as you described on https://github.com/vasern/vasern/issues/7 

Can you help me to clarify things below?

1. If not already, make sure the `Document.import(Queryable)` is at the end of `Document.js`

2. Since it compain about `metro-react-native-babel-preset`, have you got it on your `package.json`, under `devDependencies`? If not, install and save it to `dev`
```
npm install --save-dev metro-react-native-babel-preset
```
Once you complete, start your project and see if the error is still there. If it does, then go to the next step.

3. Setup your project using `[metro-react-native-babel-preset](https://www.npmjs.com/package/metro-react-native-babel-preset)`.  If your project has already use other babel preset, you might get complain in your current apps.

Create a `.babelrc` in the root of the project, and add this line
```json
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

Let me know how it goes!

**Comment by apppro123** [comment]
Now it works (after i updatet react-native and babel).
I have another question: Which permissions does vasern need?

**Comment by hieunc229** [comment]
Great!
I am not sure which permission you want to know. Currently, Vasern doesn't require any permission in either application settings or input/output data files.

**Comment by apppro123** [comment]
Ok, thank you!

**Comment by hieunc229** [comment]
No worries, I'm glad it helps!

Since you have solved the problem by update react-native and babel. I'll go ahead and close this issue. Feel free to reopen or create another issue :)

**Comment by apppro123** [comment]
Yes, perfect ty!
