### ISSUE TITLE
Feature: Encryption option

### ISSUE THREAD

**Issue by m-dary-nur** [vasern/vasern#78]
Hi, do you think add encryption like aes 256 into vasern option ?, Or hava any right way practice to adding encryption data locally ?

Thank you

**Comment by hieunc229** [comment]
Hey @m-dary-nur. What are you using encryption for?

I found a few libraries that could help with the encryption

**Comment by qesya** [comment]
Hi @hieunc229 , im using aes256, can you put some example to implement with vasern, please?

Thanks

**Comment by m-dary-nur** [comment]
Yes @hieunc229 using aes 256, can you make a practice how to use encryption in vasern ?, Thank you

**Comment by hieunc229** [comment]
Hey, @m-dary-nur!

 AES-256 encryption require a `password` to encrypt and decrypt. You will either:
1. Let users enter the `password` (only people with `password` can read the data)
2. Store the `password` in the device internal or a secure storage

Which senario are you in?

_Note: Vasern doesn't support data encryption. The question to understand the senario, to see if I can help_

**Comment by m-dary-nur** [comment]
Hi @hieunc229,
For point 1 , i prefer second one 
For point 2, sure, its also encrypt on the server

**Comment by hieunc229** [comment]
Ok, I still have some more questions to clarify. In general, you can encrypt data like as the below example:

_I'll be using [crypto-js](https://www.npmjs.com/package/crypto-js) in this example. This should works on any javascript enviroment (React Native, nodejs, ...)_

```js
import crypto from "crypto-js";

// encryption password, need to store somewhere safe
const secretKey = `randomkey`;
const message = `Hello World`;

// To encrypt
const encryptedText = crypto.AES.encrypt(message, secretKey).toString();
 
// To decrypt
const bytes  = crypto.AES.decrypt(encryptedText, secretKey);
const decryptedText = bytes.toString(crypto.enc.Utf8);

console.log(decryptedText) // => `Hello World`
```

The problem here is where to store the `secretKey` to avoid people checking out the password. Basically, data stored in `vasern` is private to the application (other apps can't read it). Though, there is a small but rare chance of someone will get the data file, and look for the password.

If you are still confuse, let's have a chat on our Slack channel here https://join.slack.com/t/vasern/shared_invite/zt-5uoc8hec-Y~b9PjQfN0n2PbCTJH7exA

**Comment by m-dary-nur** [comment]
Thank you @hieunc229 , but what is it possible to use encryption like crypto within vasern configdb parameter like

`new Vasern({schemas: [...], encryption: { secretKey: 'someKey', type: 'sha256' }});`

Sure, actually i've joined vasern channel on slack

**Comment by hieunc229** [comment]
We had a chat on slack channel so I'll close this thread. Feel free to re-open or create a new thread

**Comment by m-dary-nur** [comment]
Thanks @hieunc229 , sorry im forget to close it
