### ISSUE TITLE
Numbers inserted as strings

### ISSUE THREAD

**Issue by dmitryuck** [vasern/vasern#82]
when I try to insert object like this {"code": "en", "name": "English", "index": 145634}
then read it from store "index" returns as string "145634"

if change this line in sources numbers saving as numbers
Document.js - line 208: content[k] = kValue;//.toString();

**Comment by hieunc229** [comment]
Hey Dmitry, thanks for reporting the issue. I'll make a fix ASAP!

**Comment by hieunc229** [comment]
This issue has been around a for while. It used to be `kValue` (without `toString), which caused some other issues that I forgot. I've pushed an update to fix this one.

_Note that there isn't a type `number`. Numbers are in `int` or `double` only. Otherwise, it might parse the result as `string`_

Let me know if the issue still persists
